#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdlib.h>
#include <unistd.h>
#include <string.h>

typedef unsigned int uint;

enum ENUM_MSG_TYPE
{
    ENUM_MSG_TYPE_MIN = 0,
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_ALL_ONLINE_REQUEST,
    ENUM_MSG_TYPE_ALL_ONLINE_RESPOND,
    ENUM_MSG_TYPE_SEARCH_USR_REQUEST,
    ENUM_MSG_TYPE_SEARCH_USR_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_AGREE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_REFUSE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_FLUSH_RFIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_RFIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_RFIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_RFIEND_RESPOND,
    ENUM_MSG_TYPE_PRIVATE_CHAT_REQUEST,
    ENUM_MSG_TYPE_PRIVATE_CHAT_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_CREAT_DIR_REQUEST,
    ENUM_MSG_TYPE_CREAT_DIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DELETE_REQUEST,
    ENUM_MSG_TYPE_DELETE_RESPOND,
    ENUM_MSG_TYPE_RENAME_REQUEST,
    ENUM_MSG_TYPE_RENAME_RESPOND,
    ENUM_MSG_TYPE_FILE_INTO_REQUEST,
    ENUM_MSG_TYPE_FILE_INTO_RESPOND,
    ENUM_MSG_TYPE_FILE_BACK_REQUEST,
    ENUM_MSG_TYPE_FILE_BACK_RESPOND,
    ENUM_MSG_TYPE_UPDATE_REQUEST,
    ENUM_MSG_TYPE_UPDATE_RESPOND,
    ENUM_MSG_TYPE_UPDATE_SUCCESS_RESPOND,
    ENUM_MSG_TYPE_DOWNLOAD_REQUEST,
    ENUM_MSG_TYPE_DOWNLOAD_RESPOND,
    ENUM_MSG_TYPE_START_DOWNLOAD_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_NOTE,
    ENUM_MSG_TYPE_SHARE_FILE_NOTE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_NOTE_RESPOND_SENDER,
    ENUM_MSG_TYPE_SHARE_FILE_NOTE_RESPOND_RECEIVER,

    SERVER_SHUTDOWN,
    ENUM_MSG_TYPE_MAX = 0x00ffffff,
};

struct PDU
{
    uint uiPDULen,uiMsgType;
    char caData[64];
    uint uiMsgLen;
    char caMsg[];
};

PDU *mkPDU(uint uiMsgLen);

#endif // PROTOCOL_H
